Called try block 0
Called finally block 0
Uncaught NewException, code: 1
Message: Catch me once
Called finally block 1
Called finally block 2
Uncaught NewException, code: 2
Message: Catch me twice
Uncaught Exception, code: 3
Message: Catch me thrice